# Generated by Django 5.1.2 on 2025-11-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie_details',
        ),
    ]
