# Generated by Django 5.1.2 on 2025-11-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0002_delete_movie_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100, unique=True)),
                ('relase_date', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
