# Generated by Django 5.1.2 on 2025-11-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_details',
            old_name='relase_date',
            new_name='realse_date',
        ),
    ]
