# Generated by Django 5.1.2 on 2025-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_relase_date_movie_details_realse_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_details',
            name='rating',
            field=models.CharField(max_length=100),
        ),
    ]
