# Generated by Django 5.1.2 on 2025-11-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_movie_details_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_details',
            old_name='realse_date',
            new_name='release_date',
        ),
    ]
